DROP SEQUENCE IF EXISTS "author_id seq";
CREATE SEQUENCE "author_id seq" INCREMENT BY 50 START WITH 1;

DROP SEQUENCE IF EXISTS "authors";
CREATE TABLE "authors" (
    "id" bigint NOT NULL,
    "age" smallint,
    "description" VARCHAR(512),
    "image" VARCHAR(512),
    "name" VARCHAR(512),
    CONSTRAINT "authors_pkey" PRIMARY KEY("id")
);

CREATE TABLE author (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS SEQUENCE author_id_seq,
    name VARCHAR(255) NOT NULL,
    age INTEGER NOT NULL,
    description TEXT NOT NULL,
    image TEXT NOT NULL
);